#!/bin/bash

# nginx-maintenance init script
# https://github.com/stvnwrgs/nginx-maintenance

cd "/etc/nginx/sites-enabled"

case "$1" in
    start)
        ln -s ../sites-available/000-maintenance 000-maintenance
        /etc/init.d/nginx reload
        ;;
    stop)
        rm 000-maintenance
        /etc/init.d/nginx reload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
